cc_test(
   name = "my_gtest",
   srcs = ["my_gtest.cc"],
   deps = ["@com_google_test//:gtest_main"],
)

cc_test(
   name = "my_gmock",
   srcs = ["my_gmock.cc"],
   deps = ["@com_google_test//:gtest_main"],
)

cc_test(
   name = "adv_mygmock",
   srcs = ["adv_mygmock.cc"],
   deps = ["@com_google_test//:gtest_main"],
)
cc_test(
   name = "test_p",
   srcs = ["test_p.cc"],
   deps = ["@com_google_test//:gtest_main"],
)
