#load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
cc_binary(
  name = "new_delete",
  srcs = ["new_delete.cc"],
)

cc_binary(
  name = "mem_excep",
  srcs = ["mem_excep.cc"],
)

cc_binary(
  name = "mem_overload",
  srcs = ["mem_overload.cc"],
)
