#load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
cc_binary(
  name = "gdb_sample",
  srcs = ["gdb_sample.cc"],
)

cc_binary(
  name = "gdb_loop_sample",
  srcs = ["gdb_loop_sample.cc"],
)
