#load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
cc_binary(
  name = "vector",
  srcs = ["vector.cc"],
)

cc_binary(
  name = "map",
  srcs = ["map.cc"],
)

cc_binary(
  name = "list",
  srcs = ["list.cc"],
)
