#load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
cc_binary(
  name = "shared_node_tree",
  srcs = ["shared_node_tree.cc"],
)

cc_binary(
  name = "shared_ptr",
  srcs = ["shared_ptr.cc"],
)

cc_binary(
  name = "del_shared_ptr",
  srcs = ["del_shared_ptr.cc"],
)

cc_binary(
  name = "unique_ptr",
  srcs = ["unique_ptr.cc"],
)
